Homework lesson Objects
avt191540/homework1 pull request #7
Opened 2021-11-06 22:04 UTC by avt191540

Homework lesson Objects is done

2021-11-07 23:01 UTC, DisterRU requested changes

2021-11-07 23:01 UTC, DisterRU commented on src/pro/sky/java/course1/lessonObjects/Library.java
> +                System.out.println(this.books[i].getPublishingYear());
Печатать здесь не требуется.

2021-11-07 23:01 UTC, DisterRU commented on src/pro/sky/java/course1/lessonObjects/Library.java
> +                System.out.println(this.books[i].getPublishingYear());
this следует убрать.

2021-11-07 23:01 UTC, DisterRU commented on src/pro/sky/java/course1/lessonObjects/MainObjects.java
> +
Т.к. был реализован уровень сложнее, эти методы следует удалить из класса MainObjects.

2021-11-10 08:17 UTC, avt191540 commented on src/pro/sky/java/course1/lessonObjects/MainObjects.java
> +
Всё исправил, повторно отправил на проверку

2021-11-10 18:04 UTC, DisterRU approved these changes

2021-11-10 18:04 UTC, DisterRU commented on src/pro/sky/java/course1/lessonObjects/Author.java
> +    private final String LastName;
Имена переменных в Java начинаются с маленькой буквы.

2021-11-10 18:39 UTC, merged